import { CompanyTypeOption } from './types';

export const COMPANY_TYPES: CompanyTypeOption[] = [
  { id: 10, name: "Adult Novelties" },
  { id: 31, name: "Amusement Park" },
  { id: 8, name: "Candle Shop" },
  { id: 4, name: "Car Dealership" },
  { id: 5, name: "Clothing Store" },
  { id: 15, name: "Cruise Line" },
  { id: 11, name: "Cyber Cafe" },
  { id: 39, name: "Detective Agency" },
  { id: 34, name: "Farm" },
  { id: 19, name: "Firework Stand" },
  { id: 29, name: "Fitness Center" },
  { id: 3, name: "Flower Shop" },
  { id: 21, name: "Furniture Store" },
  { id: 7, name: "Game Shop" },
  { id: 22, name: "Gas Station" },
  { id: 26, name: "Gents Strip Club" },
  { id: 12, name: "Grocery Store" },
  { id: 6, name: "Gun Shop" },
  { id: 1, name: "Hair Salon" },
  { id: 36, name: "Ladies Strip Club" },
  { id: 2, name: "Law Firm" },
  { id: 32, name: "Lingerie Store" },
  { id: 40, name: "Logistics Management" },
  { id: 33, name: "Meat Warehouse" },
  { id: 30, name: "Mechanic Shop" },
  { id: 38, name: "Mining Corporation" },
  { id: 23, name: "Music Store" },
  { id: 24, name: "Nightclub" },
  { id: 28, name: "Oil Rig" },
  { id: 37, name: "Private Security Firm" },
  { id: 20, name: "Property Broker" },
  { id: 25, name: "Pub" },
  { id: 27, name: "Restaurant" },
  { id: 35, name: "Software Corporation" },
  { id: 14, name: "Sweet Shop" },
  { id: 16, name: "Television Network" },
  { id: 13, name: "Theater" },
  { id: 9, name: "Toy Shop" },
  { id: 18, name: "Zoo" },
];

export const CACHE_KEY_PREFIX = 'torn_company_data_';
